import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import { Header } from "@/components/Header";
import { Toaster } from "sonner";
import Provider from "@/hooks/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <Provider>
          <Header />
          <main className="w-full lg:px-6 lg:max-w-[1280px] lg:mx-auto">
            {children}
          </main>
          <Toaster position="top-right" />
        </Provider>
      </body>
    </html>
  );
}

